import { useState, useEffect } from "react";
import { db } from "./firebase";
import {
  collection,
  addDoc,
  onSnapshot,
  deleteDoc,
  doc
} from "firebase/firestore";

function App() {
  const [tasks, setTasks] = useState([]);
  const [newTask, setNewTask] = useState("");

  // TODO: Listen to Firestore collection "tasks" in real time
  useEffect(() => {
    // onSnapshot is a firebase function that sets up a real-time listener to a collection
    // snapshot contains currnet state of documents, map over array of documents
    // unique ID generated by Firestore
    // merge ID with data
    const unsub = onSnapshot(collection(db, "tasks"), (snapshot) => {
      setTasks(snapshot.docs.map(doc => ({id: doc.id, ...doc.data() })));
    });
    return () => unsub();
  }, []);

  // TODO: Add new task
  const addTask = async () => {
    // addDoc is another Firebase function to add a document to a collection
    // takes reference to collection, data object to store
    // clear input field after task added 
    if (newTask.trim() === "") return;
    await addDoc(collection(db, "tasks"), {text: newTask});
    setNewTask("");
  };

  // TODO: Delete task
  const deleteTask = async (id) => {
    // deleteDoc is another Firebase function to rmemove document 
    // takes reference to document to delete 
    await deleteDoc(doc(db, "task", id));
  };

  return (
    <div style={{ maxWidth: 400, margin: "auto", padding: 20 }}>
      <h1>To-Do List</h1>
      <input
        value={newTask}
        onChange={(e) => setNewTask(e.target.value)}
        placeholder="New task..."
      />
      <button onClick={addTask}>Add</button>

      <ul>
        {tasks.map(task => (
          <li key={task.id}>
            {task.text}{" "}
            <button onClick={() => deleteTask(task.id)}>X</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;